// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDobDdb5dhlxkdT-X1y8HuELeXpT8YlO4U',
    appId: '1:443543448580:web:e0dc0f4aacedae33c7d951',
    messagingSenderId: '443543448580',
    projectId: 'expense-tracker-app-7f353',
    authDomain: 'expense-tracker-app-7f353.firebaseapp.com',
    storageBucket: 'expense-tracker-app-7f353.firebasestorage.app',
    measurementId: 'G-3RXHGWD8DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEi7VwF2ioeMM3rF0vr_DARpMpIbALtbc',
    appId: '1:443543448580:android:bca73f243e45680ac7d951',
    messagingSenderId: '443543448580',
    projectId: 'expense-tracker-app-7f353',
    storageBucket: 'expense-tracker-app-7f353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMXbPVpU6pQsH3IvE3MyVe-dlhnhj3Ahw',
    appId: '1:443543448580:ios:4a03c72234d37c19c7d951',
    messagingSenderId: '443543448580',
    projectId: 'expense-tracker-app-7f353',
    storageBucket: 'expense-tracker-app-7f353.firebasestorage.app',
    iosBundleId: 'com.expense.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMXbPVpU6pQsH3IvE3MyVe-dlhnhj3Ahw',
    appId: '1:443543448580:ios:4a03c72234d37c19c7d951',
    messagingSenderId: '443543448580',
    projectId: 'expense-tracker-app-7f353',
    storageBucket: 'expense-tracker-app-7f353.firebasestorage.app',
    iosBundleId: 'com.expense.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDobDdb5dhlxkdT-X1y8HuELeXpT8YlO4U',
    appId: '1:443543448580:web:1bf3b80948d3c49fc7d951',
    messagingSenderId: '443543448580',
    projectId: 'expense-tracker-app-7f353',
    authDomain: 'expense-tracker-app-7f353.firebaseapp.com',
    storageBucket: 'expense-tracker-app-7f353.firebasestorage.app',
    measurementId: 'G-HRTPNPMKSZ',
  );
}
